occ_site/GestionStagiaires/urls.py
from django.urls import path
from . import views

app_name = 'GestionStagiaires' 
urlpatterns = [  
    #path('', views.admins, name='admins'),
    #ex: /GestionStagiaires/
    path('', views.index, name='index'),
    #ex: /GestionStagiaires/createStagiaire 
    path('createStagiaire/', views.createStagiaire, name='createStagiaire'), 
    #ex: /GestionStagiaires/StagiaireUPDATE/id/
    path('StagiaireUPDATE/<int:id>/',views.createStagiaire, name='StagiaireUPDATE'),
    #ex: /GestionStagiaires/stagiaireConfirmEnregistrement
    path('stagiaireConfirmEnregistrement',views.stagiaireConfirmEnregistrement, name='stagiaireConfirmEnregistrement'),   
    #ex: /GestionStagiaires/listeStagiaires 
    path('listeStagiaires/', views.listeStagiaires, name='listeStagiaires'), 
    #ex: /GestionStagiaires/deleteStagiaire/id/ 
    path('deleteStagiaire/<str:pk>/', views.deleteStagiaire, name='deleteStagiaire'),  

    #ex: /GestionStagiaires/annoce
    path('annoce/', views.annoce, name='annoce'),
    #ex: /GestionStagiaires/contactMassage/
    path('contactMessage/', views.contactMessage, name='contactMessage'), 
    #ex: /GestionStagiaires/resultMessage/
    path('resultMessage/', views.resultMessage, name='resultMessage'),  
    path('<int:id>/', views.index, name='stagiaire_update'),  

    #Encadreur
    #ex: /GestionStagiaires/CreateEncadreur/
    path('CreateEncadreur/', views.CreateEncadreur, name='CreateEncadreur'),
    #ex: /GestionStagiaires/CreateEncadreurAjax/
    path('CreateEncadreurAjax/', views.CreateEncadreurAjax, name='CreateEncadreurAjax'),
    #ex: /GestionStagiaires/UpdateEncadreur/
    path('UpdateEncadreur/<int:id>/', views.CreateEncadreur, name='UpdateEncadreur'),
    #ex: /GestionStagiaires/listesEncadreur/
    path('listesEncadreur/', views.listesEncadreur, name='listesEncadreur'),
    #ex: /GestionStagiaires/deleteEncadreur/
    path('deleteEncadreur/<int:id>/', views.deleteEncadreur, name='deleteEncadreur'),

    #Direction
    #ex: /GestionStagiaires/CreateDirection/
    path('CreateDirection/', views.CreateDirection, name='CreateDirection'),
    #ex: /GestionStagiaires/CreateDirectionAjax/
    path('CreateDirectionAjax/', views.CreateDirectionAjax, name='CreateDirectionAjax'),
    path('CreateDirectionAjaxs/<str:id>/', views.CreateDirectionAjax, name='CreateDirectionAjaxs'),

    #ex: /GestionStagiaires/UpdateDirection/id/
    path('UpdateDirection/<int:id>/', views.CreateDirection, name='UpdateDirection'),
    #ex: /GestionStagiaires/deleteDirection/id/
    path('deleteDirection/<int:id>/', views.deleteDirection, name='deleteDirection'),
    #ex: /GestionStagiaires/listeDirections/
    path('listeDirections/', views.listeDirections, name='listeDirections'),

    #Register Count
    #ex: /GestionStagiaires/register/
    path('register/', views.registerCount, name='registerCount'),
    #ex: /GestionStagiaires/login/
    path('login/', views.loginConnect, name='login'),
    #ex: /GestionStagiaires/login/
    path('logout/', views.logoutUser, name='logout'),
    #ex: /GestionStagiaires/Dashboard/
    path('dashboard/', views.dashBoard, name='dashbord'),
]

occ_site/occ_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('GestionStagiaires.urls')), #GestionStagiaires/
    path('admin/', admin.site.urls), 
]

occ_site/GestionStagiaires/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import ContactMessage, Stagiaire, Encadreur, Direction

class ContactMessageForm(forms.ModelForm):
    class Meta:
        model = ContactMessage
        fields = ('Email','nom','msg')  
        labels = {
            'Email':'Entrez votre mail',
            'nom':'Entrez nom complet',
            'msg':'Ecrire votre message'
        }
        #widgets = {
        #    'msg': textarea()
        #}
    #def __init__(self, *args, **kwargs):
        #super(ContactMessageForm,self).__init__(*args, **kwargs)
        #self.fields['nom'].empty_label = "votre nom"

class EncadreurForm(forms.ModelForm):
    class Meta:
        model = Encadreur
        fields = ('nom_encad','postnom_encad','prenom_encad','sexe_encad')
        labels = {
            'nom_encad': 'Nom',
            'postnom_encad':'Postnom',
            'prenom_encad': 'Prenom',
            'sexe_encad':'Sexe'
        }
        

    #def __init__(self, *args, **kwargs):
    #    super(EncadreurForm,self).__init__(*args,  **kwargs)
    #    self.fields['nom_encad'].

class StagiaireForm(forms.ModelForm):
    class Meta: 
        model = Stagiaire
        fields = ('nom_stagiaire','postnom_stagiaire','prenom_stagiaire','sexe_stagiaire','email_stagiaire','adresse_stagiaire','telephone_stagiaire','type_stage','promotion_stagiaire','direction','encadreur') #'__all__'
        labels = {
            'nom_stagiaire': 'Nom',
            'postnom_stagiaire':'Postnom',
            'prenom_stagiaire':'Prenom',
            'sexe_stagiaire':'Sexe',
            'email_stagiaire':'Email',
            'adresse_stagiaire':'Adresse',
            'telephone_stagiaire':'Telephone',
            'type_stage':'Type de Stage',
            'promotion_stagiaire':'Promotion Stagiaire',
            #'direction':'Direction De Stagiaire',
            #'encadreur':'Encadreur De Stage'
        } 
        widgets = {
            'direction':forms.Select(attrs={'class':'listDirection'})
        }

    def __init__ (self, *args, **kwargs):
        super(StagiaireForm,self).__init__(*args,**kwargs)
        self.fields['direction'].empty_label = "Select Direction"
        self.fields['encadreur'].empty_label = "Select Encadreur"

class DirectionForm(forms.ModelForm):
    class Meta:
        model = Direction
        fields = ('nom_direction',) #'__all__'
        labels = {
            'nom_direction': 'NOM DIRECTION'
        }
        widgets = {
            'nom_direction':forms.TextInput(attrs={'class':'form-control', 'id':'NomDirection'})
        }
        
    def __init__(self, *args, **kwargs):
        super(DirectionForm,self).__init__(*args,**kwargs)
        self.fields['nom_direction'].empty_label = "Select"

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

occ_site/GestionStagiaires/views.py
from django.shortcuts import render, redirect
from .forms import ContactMessageForm, StagiaireForm, EncadreurForm, DirectionForm, CreateUserForm
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.template import loader
from .models import ContactMessage, Stagiaire, Encadreur, Direction
from django.contrib.auth.forms import UserCreationForm
#from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login, logout 
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.
def contactMessage(request):
    mail = request.POST['mail']
    nom = request.POST['nom']
    msg = request.POST['msg']
    return HttpResponse("Hello form %s "% msg) 

def index(request, id=0):
    #return HttpResponse("Hello M.si-pro")  https://docs.djangoproject.com/fr/3.1/topics/forms/https://docs.djangoproject.com/fr/3.1/topics/forms/
    # j'importe le form de la class forms.py
    if request.method =="GET":
        if id == 0:
            form = aff_form()
        else:
            ctm = ContactMessage.objects.get(pk=id)
            form = ContactMessageForm(instance=ctm)
        return render(request, 'GestionStagiaires/index.html',{'form':form}) 
    else: 
        form = ContactMessageForm(request.POST)
        if form.is_valid(): 
            form.save() 
        return redirect('/GestionStagiaires/resultMessage')

def createStagiaire(request,id=0):  
    if request.method == "GET":
        if id==0:
            context = {
                'stagiaireForm' :StagiaireForm(),
                'form' : ContactMessageForm(),
                'directionForm':DirectionForm(),
                'EncadreurForm': EncadreurForm()
            }
            return render(request,'GestionStagiaires/Etudiant/createStagiaire.html', context)
        else:
            #recuperation d'un seul stagiaire
            stagiaire = Stagiaire.objects.get(pk=id)
            #stagiaireForm = StagiaireForm(instance=stagiaire)
            context = {
                'stagiaireForm' :StagiaireForm(instance=stagiaire),
                'form' : ContactMessageForm(),
                'directionForm':DirectionForm(),
                'EncadreurForm': EncadreurForm()
            }
        return render(request,'GestionStagiaires/Etudiant/createStagiaire.html', context)
    else:
        if id==0:
            stagiaireForm = StagiaireForm(request.POST)
            if stagiaireForm.is_valid():
                stagiaireForm.save()
                context = {
                    'Messages': 'Enregistrement Effectué avec succes'
                }
                return render(request, 'GestionStagiaires/Etudiant/stagiaireConfirmEnregistrement.html', context)
            else :
                context = {
                    'Messages': 'Echec Enregistrement'
                } 
                return render(request, 'GestionStagiaires/Etudiant/stagiaireConfirmEnregistrement.html', context)
        else:
            stagiaire = Stagiaire.objects.get(pk=id)
            stagiaireForm = StagiaireForm(request.POST,instance=stagiaire)
            if stagiaireForm.is_valid():
                stagiaireForm.save()
                context = {'Messages': 'Modification Stagiaire Effectué avec Success',}
                return render(request, 'GestionStagiaires/Etudiant/stagiaireConfirmEnregistrement.html', context) 
            else:
                context = {'Messages': 'Modification Stagiaire a Echoué',}
                return render(request, 'GestionStagiaires/Etudiant/stagiaireConfirmEnregistrement.html', context) 
   
def deleteStagiaire(request, pk):
    stagiaire = Stagiaire.objects.get(id=pk)
    context = {
        'Stagiaires_liste': Stagiaire.objects.all(),
        'form':ContactMessageForm(),
        'stagiaireForm' :stagiaire
    }
    if request.method == "POST":
        stagiaire.delete()
        return render(request, 'GestionStagiaires/Etudiant/listeStagiaires.html', context)
    return render(request, 'GestionStagiaires/Etudiant/deleteStagiaire.html', context)

def stagiaireConfirmEnregistrement(request):
    return render(request, 'GestionStagiaires/Etudiant/stagiaireConfirmEnregistrement.html')


def listeStagiaires(request):
    context = {
        'Stagiaires_liste': Stagiaire.objects.all(),
        'form':ContactMessageForm()
    }
    return render(request, 'GestionStagiaires/Etudiant/listeStagiaires.html', context)

def resultMessage(request):
    form = aff_form() 
    context = {
        'ContactMessage_list':ContactMessage.objects.all(),
        'form':form
    }
    return render(request, 'GestionStagiaires/resultMessage.html', context)

def annoce(request):
    return HttpResponse("Hello M.si-pro") 

def aff_form():
    return ContactMessageForm() 


def CreateEncadreur(request, id=0):
    if request.method == "GET":
        if id==0:            
            context = {
                'EncadreurForm': EncadreurForm(),
                'form':ContactMessageForm()
            }
            return render(request, 'GestionStagiaires/Encadreur/AddEncadreur.html', context)
        else:            
            encadreurForm = Encadreur.objects.get(pk=id)
            context = {
                'EncadreurForm': EncadreurForm(instance=encadreurForm),
                'form':ContactMessageForm()
            }
            return render(request, 'GestionStagiaires/Encadreur/AddEncadreur.html', context)
    elif request.method == "POST":
        if id == 0:
            encadreur = EncadreurForm(request.POST)
            if encadreur.is_valid():
                encadreur.save()
                context = { 'Messages': "Enregistrement ENCADREUR Effectué avec success"}
                return render(request, 'GestionStagiaires/Encadreur/EncadreurConfirmMessage.html', context)
            else:
                context = { 'Messages': "Echec d'Enregistrement"}
            return render(request, 'GestionStagiaires/Encadreur/EncadreurConfirmMessage.html', context)
        else:
            encadreurForm = Encadreur.objects.get(pk=id)
            encadreur = EncadreurForm(request.POST,instance=encadreurForm)
            if encadreur.is_valid():
                encadreur.save()
                context = { 'Messages': "Mise ajour Encadreur Effectué avec Success"} 
                return render(request, 'GestionStagiaires/Encadreur/EncadreurConfirmMessage.html', context)
            else:
                context = { 'Messages': "Echec de Mise ajour"}
                return render(request, 'GestionStagiaires/Encadreur/EncadreurConfirmMessage.html', context)
    else:
        context = {
            'EncadreurForm': EncadreurForm(),
            'form':ContactMessageForm()
        }
        return render(request, 'GestionStagiaires/Encadreur/AddEncadreur.html', context)

def listesEncadreur(request):
    context = {
        'Encadreur_listes': Encadreur.objects.all(),
        'form':ContactMessageForm()
    }
    return render(request, 'GestionStagiaires/Encadreur/listesEncadreurs.html', context)

def deleteEncadreur(request, id):
    encadreur = Encadreur.objects.get(pk=id)
    context = {
        'Encadreur_listes': Encadreur.objects.all(),
        'form':ContactMessageForm(),
        'encadreur':Encadreur.objects.get(pk=id)
    }
    if request.method == "POST":
        encadreur.delete()
        return render(request, 'GestionStagiaires/Encadreur/listesEncadreurs.html', context)
    return render(request,'GestionStagiaires/Encadreur/DeleteEncadreur.html', context)

def CreateDirection(request,id=0):
    if request.method == "GET":
        if id==0:
            context = {'form':ContactMessageForm(),'directionForm':DirectionForm()
            }
            return render(request,'GestionStagiaires/Direction/AddDirection.html',context)
        else:
            direction = Direction.objects.get(pk=id)
            context = { 'form':ContactMessageForm(),'directionForm':DirectionForm(instance=direction)}
        return render(request, 'GestionStagiaires/Direction/AddDirection.html',context) 

    elif request.method == "POST":
        if id==0:
            direction = DirectionForm(request.POST)
            if direction.is_valid():
                direction.save()
                context = { 'Messages': "Enregistrement DIRECTION Effectué avec success"}
                return render(request, 'GestionStagiaires/Direction/DirectionConfirmMessage.html', context)
            else:
                context = { 'Messages': "Echec d'Enregistrement DIRECTION"}
            return render(request, 'GestionStagiaires/Encadreur/EncadreurConfirmMessage.html', context)
        else:
            directionForm = Direction.objects.get(pk=id)
            direction = DirectionForm(request.POST,instance=directionForm)
            if direction.is_valid():
                direction.save()
                context = { 'Messages': "Modification DIRECTION Effectué avec success"}
                return render(request, 'GestionStagiaires/Direction/DirectionConfirmMessage.html', context)
            else:
                context = { 'Messages': "Echec Modification DIRECTION"}
            return render(request, 'GestionStagiaires/Direction/DirectionConfirmMessage.html', context)
    else:
        return HttpResponse('Create Direct')

def deleteDirection(request, id):
    direction = get_object_or_404(Direction, pk=id) #Direction.objects.get(pk=id)
    context = {
        'direction_list': Direction.objects.all(),
        'form':ContactMessageForm(),
        'direction':get_object_or_404(Direction, pk=id)
    }
    if request.method == "POST":
        direction.delete()
        return render(request, 'GestionStagiaires/Direction/listeDirections.html', context)
    return render(request,'GestionStagiaires/Direction/deleteDirection.html', context)

def listeDirections(request):
    context = {
        'form':ContactMessageForm(),

occ_site/GestionStagiaires/templates/GestionStagiaires/Etudiant/createStagiaire.html
{% extends 'GestionStagiaires/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
  Create Stagiaires
{% endblock %}

{% block contenu %}
<div class="row">
    <div class="offset-md-2 col-md-8 bg-dark1">
        <h3 class="text-center alert alert-info">Enregistrement Stagaire</h3>
        <form action="" method="POST" autocomplete="off">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    {{stagiaireForm.nom_stagiaire|as_crispy_field}}
                </div>
                <div class="col-md-6">
                    {{stagiaireForm.postnom_stagiaire|as_crispy_field}}
                </div>
                <div class="col-md-6">
                    {{stagiaireForm.prenom_stagiaire|as_crispy_field}}
                </div>
                <div class="col-md-6">
                    {{stagiaireForm.sexe_stagiaire|as_crispy_field}}
                </div>
                <div class="col-md-6">
                    {{stagiaireForm.email_stagiaire|as_crispy_field}}
                </div>
                <div class="col-md-6">
                    {{stagiaireForm.adresse_stagiaire|as_crispy_field}}
                </div>
                <div class="col-md-6">
                    {{stagiaireForm.type_stage|as_crispy_field}}
                </div>
                <div class="col-md-2">
                    {{stagiaireForm.promotion_stagiaire|as_crispy_field}}
                </div>
                <div class="col-md-4">
                    {{stagiaireForm.telephone_stagiaire|as_crispy_field}}
                </div>
                <div class="col-md-4">
                    {{stagiaireForm.direction|as_crispy_field}}
                </div>
                <div class="col-md-2 bg-dark1 ">
                    <a id="EditLink" class="fermeLink" href="#">Edit /</a>
                    </span id="EditLink1"><a id="EditLink3" href="Lien_a_Modif.html" target="_blank"></a></span>
                <span id="EditLink5"></span>
                    <a href="#" type="button" data-toggle="modal" data-target="#staticBackdrop">Add</a>
                </div>
                <div class="col-md-4">
                    {{stagiaireForm.encadreur|as_crispy_field}}
                </div>
                <div class="col-md-2">
                    <a href="#"></a>
                    <a href="{% url 'GestionStagiaires:CreateEncadreur' %}"></a>
                    <a href="#" type="button" data-toggle="modal" data-target="#staticBackdrop1">Add</a>
                </div>
               
                    <button type="submit" class="btn btn-success form-control"><i class="fas fa-database"></i> Envoyer</button>
               
            </div>
        </form>  
        <br />     
    </div>
    </div>
    <!-- Modal pour Direction -->
    <div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <!--h5 class="modal-title" id="staticBackdropLabel">Modal title</h5-->
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">
                    <h3 class="text-center">Add DIRECTION OCC</h3>
                    <form id="formDirection" method="POST" autocomplete="off">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ directionForm.as_p }}
                        </div> 
                        <button type="submit" id="btnSave1" class="btn btn-success form-control"><i class="fas fa-database"></i> ENREGISTRER</button>                
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal pour Encadreur -->
    <div class="modal fade" id="staticBackdrop1" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <!--h5 class="modal-title" id="staticBackdropLabel">Modal title</h5-->
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">
                    <h3 class="text-center">Add Encadreur OCC</h3>
                    <form id="" method="POST" autocomplete="off">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ EncadreurForm.nom_encad|as_crispy_field }}
                        </div>  
                        <div class="form-group">
                            {{ EncadreurForm.postnom_encad|as_crispy_field }}
                        </div> 
                        <div class="form-group">
                            {{ EncadreurForm.prenom_encad|as_crispy_field }}
                        </div>
                        <div class="form-group">
                            {{ EncadreurForm.sexe_encad|as_crispy_field }}
                        </div> 
                        <button type="submit" id="btnSaveEncad" class="btn btn-success form-control"><i class="fas fa-database"></i> Envoyer</button>                
                    </form>
                </div>
                </div-->
            </div>
        </div>
    </div>
{% endblock %}  

occ_site/GestionStagiaires/templates/GestionStagiaires/Etudiant/deleteStagiaire.html
<h3>Vous voulais supprimer cette element {{ stagiaireForm }}</h3>
<form action="{% url 'GestionStagiaires:deleteStagiaire' stagiaireForm.id %}" method="POST">
    {% csrf_token %}
    <a href="{% url 'GestionStagiaires:listeStagiaires' %}">Cancel</a>
    <input type="submit" value="Confirm" name="Confirm" />
</form>

occ_site/GestionStagiaires/templates/GestionStagiaires/Etudiant/listeStagiaires.html
{% extends 'GestionStagiaires/base.html' %}

{% block title %}
   Listes Stagiaires
{% endblock %}

{% block contenu %}
<br /> 
    <h3 class="text-center alert alert-info">LISTE DES STAGIAIRES DE L'OCC</h3>
    <table class="table table-borderless">
       <thead class="border-bottom font-weight-bold">
            <tr>
                <th>Num</th>
                <td>Nom</td>
                <td>Postnom</td>
                <td>Prenom</td>
            </tr>
       </thead> 
       <tbody>
            {% for Stg in Stagiaires_liste%}
                <tr>
                    <td>{{ Stg.id }}</td>
                    <td>{{ Stg.nom_stagiaire }}</td>
                    <td>{{ Stg.postnom_stagiaire }}</td>
                    <td>{{ Stg.prenom_stagiaire }}</td>
                    <td><span><a href="{% url 'GestionStagiaires:deleteStagiaire' Stg.id %}">Del</a></span></td>
                    <td><span><a href="{% url 'GestionStagiaires:StagiaireUPDATE' Stg.id %}">Edit</a></span></td>
                </tr>
           {% endfor %}
       </tbody>
    </table>
{% endblock %}  

occ_site/GestionStagiaires/templates/GestionStagiaires/Etudiant/stagiaireConfirmEnregistrement.html
<h1>{{ Messages }}</h1>
<h3><a href="{% url 'GestionStagiaires:createStagiaire' %}">Retour</a></h3>