occ_site/GestionStagiaires/urls.py
from django.urls import path
from . import views

app_name = 'GestionStagiaires' 
urlpatterns = [  
    #path('', views.admins, name='admins'),
    #ex: /GestionStagiaires/
    path('', views.index, name='index'),
    #ex: /GestionStagiaires/createStagiaire 
    path('createStagiaire/', views.createStagiaire, name='createStagiaire'), 
    #ex: /GestionStagiaires/StagiaireUPDATE/id/
    path('StagiaireUPDATE/<int:id>/',views.createStagiaire, name='StagiaireUPDATE'),
    #ex: /GestionStagiaires/stagiaireConfirmEnregistrement
    path('stagiaireConfirmEnregistrement',views.stagiaireConfirmEnregistrement, name='stagiaireConfirmEnregistrement'),   
    #ex: /GestionStagiaires/listeStagiaires 
    path('listeStagiaires/', views.listeStagiaires, name='listeStagiaires'), 
    #ex: /GestionStagiaires/deleteStagiaire/id/ 
    path('deleteStagiaire/<str:pk>/', views.deleteStagiaire, name='deleteStagiaire'),  

    #ex: /GestionStagiaires/annoce
    path('annoce/', views.annoce, name='annoce'),
    #ex: /GestionStagiaires/contactMassage/
    path('contactMessage/', views.contactMessage, name='contactMessage'), 
    #ex: /GestionStagiaires/resultMessage/
    path('resultMessage/', views.resultMessage, name='resultMessage'),  
    path('<int:id>/', views.index, name='stagiaire_update'),  

    #Encadreur
    #ex: /GestionStagiaires/CreateEncadreur/
    path('CreateEncadreur/', views.CreateEncadreur, name='CreateEncadreur'),
    #ex: /GestionStagiaires/CreateEncadreurAjax/
    path('CreateEncadreurAjax/', views.CreateEncadreurAjax, name='CreateEncadreurAjax'),
    #ex: /GestionStagiaires/UpdateEncadreur/
    path('UpdateEncadreur/<int:id>/', views.CreateEncadreur, name='UpdateEncadreur'),
    #ex: /GestionStagiaires/listesEncadreur/
    path('listesEncadreur/', views.listesEncadreur, name='listesEncadreur'),
    #ex: /GestionStagiaires/deleteEncadreur/
    path('deleteEncadreur/<int:id>/', views.deleteEncadreur, name='deleteEncadreur'),

    #Direction
    #ex: /GestionStagiaires/CreateDirection/
    path('CreateDirection/', views.CreateDirection, name='CreateDirection'),
    #ex: /GestionStagiaires/CreateDirectionAjax/
    path('CreateDirectionAjax/', views.CreateDirectionAjax, name='CreateDirectionAjax'),
    path('CreateDirectionAjaxs/<str:id>/', views.CreateDirectionAjax, name='CreateDirectionAjaxs'),

    #ex: /GestionStagiaires/UpdateDirection/id/
    path('UpdateDirection/<int:id>/', views.CreateDirection, name='UpdateDirection'),
    #ex: /GestionStagiaires/deleteDirection/id/
    path('deleteDirection/<int:id>/', views.deleteDirection, name='deleteDirection'),
    #ex: /GestionStagiaires/listeDirections/
    path('listeDirections/', views.listeDirections, name='listeDirections'),

    #Register Count
    #ex: /GestionStagiaires/register/
    path('register/', views.registerCount, name='registerCount'),
    #ex: /GestionStagiaires/login/
    path('login/', views.loginConnect, name='login'),
    #ex: /GestionStagiaires/login/
    path('logout/', views.logoutUser, name='logout'),
    #ex: /GestionStagiaires/Dashboard/
    path('dashboard/', views.dashBoard, name='dashbord'),
]

occ_site/occ_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('GestionStagiaires.urls')), #GestionStagiaires/
    path('admin/', admin.site.urls), 
]

occ_site/GestionStagiaires/models.py
from django.db import models
 
# Create your models here.
class Direction(models.Model):
    nom_direction = models.CharField(max_length=100)
    def __str__(self):
        return self.nom_direction

class Encadreur(models.Model):
    nom_encad = models.CharField(max_length=20)
    postnom_encad = models.CharField(max_length=20)
    prenom_encad = models.CharField(max_length=20)
    sexe_encad = models.CharField(max_length=10)
    def __str__(self):
        return self.nom_encad +' '+ self.prenom_encad #, self.prenom_encad, self.sexe_encad

class Stagiaire(models.Model):
    nom_stagiaire = models.CharField(max_length=20)
    postnom_stagiaire = models.CharField(max_length=20)
    prenom_stagiaire = models.CharField(max_length=20)
    sexe_stagiaire = models.CharField(max_length=10)
    email_stagiaire = models.EmailField(max_length=200)
    adresse_stagiaire = models.CharField(max_length=200)
    telephone_stagiaire = models.CharField(max_length=15)
    type_stage = models.CharField(max_length=20)
    promotion_stagiaire = models.CharField(max_length=20)
    direction = models.ForeignKey(Direction, related_name='directions', on_delete=models.CASCADE)
    encadreur = models.ForeignKey(Encadreur, related_name='encadreurs', on_delete=models.CASCADE )
    #date_debut = models.DateTimeField(null=True)
    #date_debut = models.DateTimeField(auto_now_add=True)
    #date_fin = models.DateTimeField(null=True) #'date published' 2021-03-22 20:58:58.608605

    def __str__(self):
        return self.nom_stagiaire +" - "+self.postnom_stagiaire #, #prenom_stagiaire, sexe_stagiaire 

class ContactMessage(models.Model):
    nom = models.CharField(max_length=25)
    Email = models.EmailField(max_length=200)
    msg = models.CharField(max_length=200)
    #date_post = models.DateTimeField(auto_now_add=True)
    def __str__(self):
      return self.nom
    #  23/Mar/2021 23:01:55

occ_site/GestionStagiaires/views.py
from django.shortcuts import render, redirect
from .forms import ContactMessageForm, StagiaireForm, EncadreurForm, DirectionForm, CreateUserForm
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.template import loader
from .models import ContactMessage, Stagiaire, Encadreur, Direction
from django.contrib.auth.forms import UserCreationForm
#from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login, logout 
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.
def contactMessage(request):
    mail = request.POST['mail']
    nom = request.POST['nom']
    msg = request.POST['msg']
    return HttpResponse("Hello form %s "% msg) 

def index(request, id=0):
    #return HttpResponse("Hello M.si-pro")  https://docs.djangoproject.com/fr/3.1/topics/forms/https://docs.djangoproject.com/fr/3.1/topics/forms/
    # j'importe le form de la class forms.py
    if request.method =="GET":
        if id == 0:
            form = aff_form()
        else:
            ctm = ContactMessage.objects.get(pk=id)
            form = ContactMessageForm(instance=ctm)
        return render(request, 'GestionStagiaires/index.html',{'form':form}) 
    else: 
        form = ContactMessageForm(request.POST)
        if form.is_valid(): 
            form.save() 
        return redirect('/GestionStagiaires/resultMessage')

def createStagiaire(request,id=0):  
    if request.method == "GET":
        if id==0:
            context = {
                'stagiaireForm' :StagiaireForm(),
                'form' : ContactMessageForm(),
                'directionForm':DirectionForm(),
                'EncadreurForm': EncadreurForm()
            }
            return render(request,'GestionStagiaires/Etudiant/createStagiaire.html', context)
        else:
            #recuperation d'un seul stagiaire
            stagiaire = Stagiaire.objects.get(pk=id)
            #stagiaireForm = StagiaireForm(instance=stagiaire)
            context = {
                'stagiaireForm' :StagiaireForm(instance=stagiaire),
                'form' : ContactMessageForm(),
                'directionForm':DirectionForm(),
                'EncadreurForm': EncadreurForm()
            }
        return render(request,'GestionStagiaires/Etudiant/createStagiaire.html', context)
    else:
        if id==0:
            stagiaireForm = StagiaireForm(request.POST)
            if stagiaireForm.is_valid():
                stagiaireForm.save()
                context = {
                    'Messages': 'Enregistrement Effectué avec succes'
                }
                return render(request, 'GestionStagiaires/Etudiant/stagiaireConfirmEnregistrement.html', context)
            else :
                context = {
                    'Messages': 'Echec Enregistrement'
                } 
                return render(request, 'GestionStagiaires/Etudiant/stagiaireConfirmEnregistrement.html', context)
        else:
            stagiaire = Stagiaire.objects.get(pk=id)
            stagiaireForm = StagiaireForm(request.POST,instance=stagiaire)
            if stagiaireForm.is_valid():
                stagiaireForm.save()
                context = {'Messages': 'Modification Stagiaire Effectué avec Success',}
                return render(request, 'GestionStagiaires/Etudiant/stagiaireConfirmEnregistrement.html', context) 
            else:
                context = {'Messages': 'Modification Stagiaire a Echoué',}
                return render(request, 'GestionStagiaires/Etudiant/stagiaireConfirmEnregistrement.html', context) 
   
def deleteStagiaire(request, pk):
    stagiaire = Stagiaire.objects.get(id=pk)
    context = {
        'Stagiaires_liste': Stagiaire.objects.all(),
        'form':ContactMessageForm(),
        'stagiaireForm' :stagiaire
    }
    if request.method == "POST":
        stagiaire.delete()
        return render(request, 'GestionStagiaires/Etudiant/listeStagiaires.html', context)
    return render(request, 'GestionStagiaires/Etudiant/deleteStagiaire.html', context)

def stagiaireConfirmEnregistrement(request):
    return render(request, 'GestionStagiaires/Etudiant/stagiaireConfirmEnregistrement.html')


def listeStagiaires(request):
    context = {
        'Stagiaires_liste': Stagiaire.objects.all(),
        'form':ContactMessageForm()
    }
    return render(request, 'GestionStagiaires/Etudiant/listeStagiaires.html', context)

def resultMessage(request):
    form = aff_form() 
    context = {
        'ContactMessage_list':ContactMessage.objects.all(),
        'form':form
    }
    return render(request, 'GestionStagiaires/resultMessage.html', context)

def annoce(request):
    return HttpResponse("Hello M.si-pro") 

def aff_form():
    return ContactMessageForm() 


def CreateEncadreur(request, id=0):
    if request.method == "GET":
        if id==0:            
            context = {
                'EncadreurForm': EncadreurForm(),
                'form':ContactMessageForm()
            }
            return render(request, 'GestionStagiaires/Encadreur/AddEncadreur.html', context)
        else:            
            encadreurForm = Encadreur.objects.get(pk=id)
            context = {
                'EncadreurForm': EncadreurForm(instance=encadreurForm),
                'form':ContactMessageForm()
            }
            return render(request, 'GestionStagiaires/Encadreur/AddEncadreur.html', context)
    elif request.method == "POST":
        if id == 0:
            encadreur = EncadreurForm(request.POST)
            if encadreur.is_valid():
                encadreur.save()
                context = { 'Messages': "Enregistrement ENCADREUR Effectué avec success"}
                return render(request, 'GestionStagiaires/Encadreur/EncadreurConfirmMessage.html', context)
            else:
                context = { 'Messages': "Echec d'Enregistrement"}
            return render(request, 'GestionStagiaires/Encadreur/EncadreurConfirmMessage.html', context)
        else:
            encadreurForm = Encadreur.objects.get(pk=id)
            encadreur = EncadreurForm(request.POST,instance=encadreurForm)
            if encadreur.is_valid():
                encadreur.save()
                context = { 'Messages': "Mise ajour Encadreur Effectué avec Success"} 
                return render(request, 'GestionStagiaires/Encadreur/EncadreurConfirmMessage.html', context)
            else:
                context = { 'Messages': "Echec de Mise ajour"}
                return render(request, 'GestionStagiaires/Encadreur/EncadreurConfirmMessage.html', context)
    else:
        context = {
            'EncadreurForm': EncadreurForm(),
            'form':ContactMessageForm()
        }
        return render(request, 'GestionStagiaires/Encadreur/AddEncadreur.html', context)

def listesEncadreur(request):
    context = {
        'Encadreur_listes': Encadreur.objects.all(),
        'form':ContactMessageForm()
    }
    return render(request, 'GestionStagiaires/Encadreur/listesEncadreurs.html', context)

def deleteEncadreur(request, id):
    encadreur = Encadreur.objects.get(pk=id)
    context = {
        'Encadreur_listes': Encadreur.objects.all(),
        'form':ContactMessageForm(),
        'encadreur':Encadreur.objects.get(pk=id)
    }
    if request.method == "POST":
        encadreur.delete()
        return render(request, 'GestionStagiaires/Encadreur/listesEncadreurs.html', context)
    return render(request,'GestionStagiaires/Encadreur/DeleteEncadreur.html', context)

def CreateDirection(request,id=0):
    if request.method == "GET":
        if id==0:
            context = {'form':ContactMessageForm(),'directionForm':DirectionForm()
            }
            return render(request,'GestionStagiaires/Direction/AddDirection.html',context)
        else:
            direction = Direction.objects.get(pk=id)
            context = { 'form':ContactMessageForm(),'directionForm':DirectionForm(instance=direction)}
        return render(request, 'GestionStagiaires/Direction/AddDirection.html',context) 

    elif request.method == "POST":
        if id==0:
            direction = DirectionForm(request.POST)
            if direction.is_valid():
                direction.save()
                context = { 'Messages': "Enregistrement DIRECTION Effectué avec success"}
                return render(request, 'GestionStagiaires/Direction/DirectionConfirmMessage.html', context)
            else:
                context = { 'Messages': "Echec d'Enregistrement DIRECTION"}
            return render(request, 'GestionStagiaires/Encadreur/EncadreurConfirmMessage.html', context)
        else:
            directionForm = Direction.objects.get(pk=id)
            direction = DirectionForm(request.POST,instance=directionForm)
            if direction.is_valid():
                direction.save()
                context = { 'Messages': "Modification DIRECTION Effectué avec success"}
                return render(request, 'GestionStagiaires/Direction/DirectionConfirmMessage.html', context)
            else:
                context = { 'Messages': "Echec Modification DIRECTION"}
            return render(request, 'GestionStagiaires/Direction/DirectionConfirmMessage.html', context)
    else:
        return HttpResponse('Create Direct')

def deleteDirection(request, id):
    direction = get_object_or_404(Direction, pk=id) #Direction.objects.get(pk=id)
    context = {
        'direction_list': Direction.objects.all(),
        'form':ContactMessageForm(),
        'direction':get_object_or_404(Direction, pk=id)
    }
    if request.method == "POST":
        direction.delete()
        return render(request, 'GestionStagiaires/Direction/listeDirections.html', context)
    return render(request,'GestionStagiaires/Direction/deleteDirection.html', context)

def listeDirections(request):
    context = {
        'form':ContactMessageForm(),

occ_site/GestionStagiaires/templates/GestionStagiaires/ajax.html
<script>
    $(document).ready(function(){
        $("#btnSave1").click(function (e) {
            e.preventDefault();
            console.log("Save button Direction Click");
            let direction = $("#NomDirection").val();
            let csr = $("input[name=csrfmiddlewaretoken]").val();
            if(direction == ""){
                console.log('Please Enter Direction')
            }else{
                mydata = { nom_direction: direction, csrfmiddlewaretoken:csr};
            $.ajax({
                    url: "{% url 'GestionStagiaires:CreateDirectionAjax' %}",
                    method: "POST",
                    data: mydata,
                    success:function(data){
                        if(data.status == "Save"){
                            console.log("enregistrement effectué avec success");
                            console.log(data.direction_data);
                            $("#formDirection")[0].reset();
                            alert("enregistré effectué avec success"); 
                            $("#staticBackdrop").modal('hide');                       
                        }
                        else if(data.status == 0){
                            console.log("Echec D'enregistré");
                            alert("Echec D'enregistré");
                        }
                    }
                });
            }
        });

        $("#btnSaveEncad").click( function (e) {
            e.preventDefault();
            console.log('Save Button Encadreur click');
            let nom= $("#id_nom_encad").val();
            let postnom = $("#id_postnom_encad").val();
            let prenom = $("#id_prenom_encad").val();
            let sexe = $("#id_sexe_encad").val();
            let csr = $("input[name=csrfmiddlewaretoken]").val();

            if(nom == ""){
                console.log("Entre le Nom de l'encadreur");
            }else if(postnom == ""){
                console.log("Entre le prenom");
            }else if(prenom == ""){
                console.log("Entre le Prenom");
            }else if(sexe == ""){
                console.log("Entre le Sexe Encadreur");
            }
            else{
                mydata = {nom_encad:nom, postnom_encad:postnom, prenom_encad:prenom, sexe_encad:sexe, csrfmiddlewaretoken:csr}
                $.ajax({
                    url: "{% url 'GestionStagiaires:CreateEncadreurAjax' %}",
                    method: "POST",
                    data: mydata,
                    success:function(data){
                        if(data.status == "Save"){
                            console.log("enregistrement effectué avec success");
                            console.log(data.direction_data);
                            $("#formDirection")[0].reset();
                            alert("enregistré effectué avec success"); 
                            $("#staticBackdrop1").modal('hide');                       
                        }
                        else if(data.status == 0){
                            console.log("Echec D'enregistré");
                            alert("Echec D'enregistré");
                        }
                    }
                });
            }
        });

        let elt = document.getElementById('id_direction');
            elt.addEventListener('change', function(){
            let chaineVal = elt.options[elt.selectedIndex].innerHTML;
            let ab = $("#id_direction").val();
            if(chaineVal == "Select Direction" || ab == ""){
                console.log('Valeur Vide');
                document.getElementById('EditLink').className= 'fermeLink';
            }else{
                let csr = $("input[name=csrfmiddlewaretoken]").val();
                console.log(chaineVal);
                console.log(ab); 
                console.log("Un lien UPDATE: "+ "CreateDirectionAjax/"+ab);
                document.getElementById('EditLink').className= 'EditLinkss';
                
                /*let recupLink = document.getElementById('EditLink');
                recupLink.addEventListener('click', function(e) {
                    e.preventDefault();
                    e.target.href='/CreateDirectionAjaxs/'+ab;
                });*/

                //Fessaie(ab); 
                //let recupLink = 
                document.getElementById('EditLink').href='/CreateDirectionAjaxs/'+ab;
                /*let linkMod = recupLink='CreateDirectionAjaxs/'+ab;
                console.log(recupLink);*/
                /*let linKM = document.getElementById('EditLink3');
                console.log(linKM.href);*/
                /*let id = 5;
                let Aa = document.createElement('a');
                let AaText = document.createTextNode("Lienkssss");
                Aa.setAttribute('href',"CreateDirectionAjaxs/"+ab);*/
                // Aa.setAttribute('title','Edit Link');
                // Aa.id ='Edi';
                //Aa.appendChild(AaText);

                //document.getElementById('EditLink5').appendChild(Aa);

                //document.getElementById('EditLink').innerHTML = ab;
                //mydata = {nom_encad:nom, postnom_encad:postnom, prenom_encad:prenom, sexe_encad:sexe, csrfmiddlewaretoken:csr}
               /* mydata = {id_direction:ab}
                $.ajax({
                    url: "{% url 'GestionStagiaires:CreateEncadreurAjax' %}",
                    method: "GET",
                    data: mydata,
                    success:function(data){
                        if(data.status == "recup"){
                            //console.log("veleur Selec ::"+ $("#id_direction").val());
                            console.log("Recup ID avec success");
                            //console.log(data.direction_data);
                            //$("#formDirection")[0].reset();
                            //alert("enregistré effectué avec success"); 
                            //$("#staticBackdrop1").modal('hide');                       
                        }
                        else if(data.status == 0){
                            console.log("Echec Recup ID");
                            //alert("Echec D'enregistré");
                        }
                    }
                });*/
            }
              
              /*let valeur = elt.val();
              console.log(valeur);*/             
            
        });
        /*function Fessaie(ab){
            console.log("Ds F: "+ab);
        }*/

        document.getElementById('EditLink').addEventListener('click', function (e){
            e.preventDefault();
            //console.log('CONTENU: '+e.target.href);
            let Link = e.target.href;
            let csr = $("input[name=csrfmiddlewaretoken]").val();
            mydata = {csrfmiddlewaretoken:csr}
            $.ajax({
                    url: Link,
                    method: "GET",
                    //data: mydata,
                    success:function(data){
                        if(data.status == "recup"){
                            //console.log("veleur Selec ::"+ $("#id_direction").val());
                            console.log("Recup ID avec success:: "+ data.direction_data );
                            //console.log(data.direction_data);
                            //$("#formDirection")[0].reset();
                            //alert("enregistré effectué avec success"); 

                            $("#staticBackdrop").modal('show');                       
                        }
                        else if(data.status == 0){
                            console.log("Echec Recup ID");
                            //alert("Echec D'enregistré");
                        }
                    }
            });
        })
    });
</script>

occ_site/GestionStagiaires/templates/GestionStagiaires/base.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link rel="stylesheet" href="{% static 'GestionStagiaires/css/bootstrap.min.css' %}" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
		<link rel="stylesheet" href="{% static 'GestionStagiaires/css/main.css' %}">
		<title>{% block title %}{% endblock %}</title>
	</head>
	<style>
		/*#id_direction{
			color: red;
			background-color: blue;
		}*/
		#EditLink1{
			pointer-events: none;
			color: silver;
		}
		.fermeLink{
			pointer-events: none;
			color: silver;
		}
		.ouverLink{
			color: yellowgreen;
		}
	</style>
	<style>
	</style>
	<body>
		<header>	
			<div class="card">				
				<nav class="navbar navbar-expand-lg navbar-light bg-primar">
					<div class="container">
						<!-- a class="navbar-brand" href="#"><img src="{% static 'GestionStagiaires/images/logo1.jpg' %}" alt="OCC"></a-->
						<a class="navbar-brand" href="#">OCC</a>
						<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
							<span class="navbar-toggler-icon"></span>
						</button>
					
						<div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
							<ul class="navbar-nav">
								<li class="nav-item active">
									<a class="nav-link" href="{% url 'GestionStagiaires:index' %}">Accueil <span class="sr-only">(current)</span></a>
								</li>
								<!--li class="nav-item">
								<a class="nav-link" href="#">Stagiaire</a>
								</li-->
								<li class="nav-item dropdown">
									<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
										Stagiaires
									</a> 
									<div class="dropdown-menu" aria-labelledby="navbarDropdown">
										<a class="dropdown-item" href="{% url 'GestionStagiaires:annoce' %}">Annoce Stage</a> 
										<a class="dropdown-item" href="{% url 'GestionStagiaires:createStagiaire' %}">Add Stagiaires</a>
										<a class="dropdown-item" href="{% url 'GestionStagiaires:listeStagiaires' %}">Listes Stagiaires</a>
										<hr />
										<a class="dropdown-item" href="{% url 'GestionStagiaires:CreateEncadreur' %}">Add Encadreur</a>
										<a class="dropdown-item" href="{% url 'GestionStagiaires:listesEncadreur' %}">Listes Encadreur</a>
										<!--div class="dropdown-divider"></div>
										<a class="dropdown-item" href="#">Something else here</a-->
										<hr />
										<a class="dropdown-item" href="{% url 'GestionStagiaires:CreateDirection' %}">Add Direction</a>
										<a class="dropdown-item" href="{% url 'GestionStagiaires:listeDirections' %}">Listes Direction</a>
									</div>
								</li>
								<!--li class="nav-item">
									<a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Apropos</a>
								</li-->
								<li class="nav-item">
								<a class="nav-link" href="#">Apropos</a>
								</li>
								<li class="nav-item">
									<a class="nav-link" href="{% url 'GestionStagiaires:login' %}">Login</a> 
									<a class="nav-link" href="{% url 'GestionStagiaires:registerCount' %}">Create Login</a>  
								</li>
							</ul>
						</div>
					</div>
				</nav>		
			</div>
		</header>
		<section>
			<div class="container-fluid">				
					{% block contenu %}{% endblock %}
			</div>
		</section>
		
		<footer>
			<div class="container-fluid">
				<div class="row">
					<div class="col-md-4 col-lg-4 bg-primar">
						<form action="{% url 'GestionStagiaires:index' %}" method="POST" autocomplete="off">
							{% csrf_token %}
							{{ form.Email|as_crispy_field }}
							{{ form.nom|as_crispy_field }}
							{{ form.msg|as_crispy_field }}

							<button type="submit" class="btn btn-success"><i class="fas fa-database"></i> Envoyer</button>
						</form>
					</div>
					<div class="col-sm-12 col-md-4 offset-md-4 col-lg-4 offset-lg-4">
						<br />
						<!--div class="card" style="width: 18rem;">
							<div class="card-body"-->
								<!--h5 class="card-title">Laissez-Nous un message</h5-->
								<!--h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6-->
								<!--p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p-->
								<!--a href="#" class="card-link">Card link</a>
								<a href="#" class="card-link">Another link</a-->
									<!--form action="{% url 'GestionStagiaires:contactMessage' %}" method="POST">
										{% csrf_token %}
										<div class="form-group">						
										  <input type="email" name="mail" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Email address" />
										</div>
										<div class="form-group">										  
										  <input type="text" name="nom" class="form-control" id="exampleInputPassword1" placeholder="Nom complet">
										</div>
										<div class="form-group">		
											<textarea name="msg" id="" class="form-control"></textarea>
										</div>
										<button type="submit" class="btn btn-primary">Envoyer</button>
									</form-->
							<!--/div>
						</div-->
						<hr>
					</div>					
				</div>
				<div class="row">
					<div class="col-sm-12 col-md-12 col-lg-10 align-items-start">
						OCC &copy Copyright 2021
					</div>
				</div>
			</div>
		</footer>
		<!--script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script-->
		<script src="{% static 'GestionStagiaires/js/jquery-3.5.1.js' %}"></script>
		<script src="{% static 'GestionStagiaires/js/bootstrap.min.js' %}"></script>
		<script>
			var EditDisable = document.getElementById('EditDisable');
				EditDisable.disabled =true;
		</script>
		{% include "GestionStagiaires/ajax.html" %}
	</body>
</html>

occ_site/GestionStagiaires/templates/GestionStagiaires/resultMessage.html
{% extends 'GestionStagiaires/base.html' %}

{% block title %}
    Resultat
{% endblock %}

{% block contenu %}
<br />
<div class="row">
   
    <div class="col-md-12">
        <div class="jumbotron jumbotron-fluid">
            <div class="container">
              <h1 class="display-4">Message Envoyer Avec Success</h1>
              <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
                {% for stg in ContactMessage_list %}
                    <h3>{{ stg.id}} {{ stg.nom }} {{ stg.Email }} {{ stg.msg }}</h3>
                    <a href="{% url 'GestionStagiaires:stagiaire_update' stg.id %}" class="btn text-secondary px-0">
                        <i class="far fa-edit fa-lg"></i>
                    </a>
                {% endfor %}
                
            </div>
        </div>
    </div>
</div>
{% endblock %}